---
- name: Deploy Java package on Apache Tomcat locally
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  vars:
    java_package_name: java-maven4
    java_package_version: "1.1"
    tomcat_bin_dir: "/opt/tomcat/bin"
    tomcat_webapps_dir: "/opt/tomcat/webapps"
    local_git_repo_path: "/mnt/c/Users/Admin/ansible_project/publish-java-package-with-maven"
  tasks:
    - name: Ensure Tomcat bin directory exists
      stat:
        path: "{{ tomcat_bin_dir }}"
      register: tomcat_bin_stat
      failed_when: tomcat_bin_stat.stat.isdir is not defined

    - name: Stop Tomcat
      command: "{{ tomcat_bin_dir }}/shutdown.sh"
      ignore_errors: yes
      when: tomcat_bin_stat.stat.isdir

    - name: Download Java package from GitHub Packages
      uri:
        url: "https://maven.pkg.github.com/pravesh-77/publish-java-package-with-maven/com/mycompany/app4/java-maven4/1.1/java-maven4-1.1.war"
        dest: "{{ local_git_repo_path }}/target/java-maven4-1.1.war"
        method: GET
        status_code: 200
        headers:
          Authorization: "Bearer {{ github_token }}"  # Replace `github_token` with your GitHub token
      retries: 3
      delay: 10
      until: download_result is succeeded
      when: tomcat_bin_stat.stat.isdir

    - name: Move Java package to Tomcat webapps directory
      copy:
        src: "{{ local_git_repo_path }}/target/java-maven4-1.1.war"
        dest: "{{ tomcat_webapps_dir }}/{{ java_package_name }}.war"
      when: tomcat_bin_stat.stat.isdir

    - name: Start Tomcat
      command: "{{ tomcat_bin_dir }}/startup.sh"
      when: tomcat_bin_stat.stat.isdir

    - name: Initialize local Git repository
      command: "git init"
      args:
        chdir: "{{ local_git_repo_path }}"
      when: tomcat_bin_stat.stat.isdir

    - name: Commit changes to local Git repository
      shell: |
        git add target/java-maven4-1.1.war
        git commit -m "Add Java package WAR"
      args:
        chdir: "{{ local_git_repo_path }}"
        executable: /bin/bash
      when: tomcat_bin_stat.stat.isdir

    - name: Push changes to GitHub
      shell: |
        git push origin main
      args:
        chdir: "{{ local_git_repo_path }}"
        executable: /bin/bash
      become: false
      ignore_errors: yes
      when: tomcat_bin_stat.stat.isdir
