---
- name: Deploy Java package on Apache Tomcat locally
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  vars:
    java_package_name: java-maven5
    java_package_version: "1.1"
    tomcat_bin_dir: "/opt/tomcat/bin"
    tomcat_webapps_dir: "/opt/tomcat/webapps"
    github_token: "{{ lookup('env', 'GH_PACKAGE_TOKEN') }}"
  tasks:
    - name: Ensure Tomcat bin directory exists
      file:
        path: "{{ tomcat_bin_dir }}"
        state: directory
        mode: '0755'

    - name: Stop Tomcat
      command: "{{ tomcat_bin_dir }}/shutdown.sh"
      ignore_errors: true
      async: 300
      poll: 0

    - name: Wait for Tomcat to stop
      wait_for:
        path: "{{ tomcat_bin_dir }}/shutdown.sh"
        state: absent

    - name: Fetch release assets
      uri:
        url: "https://api.github.com/repos/pravesh-77/publish-java-package-with-maven/releases/latest"
        headers:
          Authorization: "Bearer {{ github_token }}"
          Content-Type: "application/json"
      register: release_info

    - name: Download WAR file from GitHub release
      get_url:
        url: "{{ item.browser_download_url }}"
        dest: "{{ tomcat_webapps_dir }}/{{ java_package_name }}.war"
        headers:
          Authorization: "Bearer {{ github_token }}"
      loop: "{{ release_info.json.assets }}"
      when: "'{{ java_package_name }}.war' in item.browser_download_url"

    - name: Start Tomcat
      command: "{{ tomcat_bin_dir }}/startup.sh"
