name: Deploy to Apache Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Java package from GitHub Packages
        run: |
          # Use GitHub CLI or another tool to download the Java package
          gh package download pravesh-77/publish-java-package-with-maven@1.2
          # Alternatively, use curl or wget to download the package

      - name: Deploy to Apache Tomcat
        run: ansible-playbook ansible_deploy.ymll
        env:
          GITHUB_TOKEN: ${{ secrets.GITUSER_TOKEN }}
