name: Publish Java Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.1
          release_name: Release 1.1
          draft: false
          prerelease: false

      - name: Upload WAR Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/java-maven4-1.1.war
          asset_name: java-maven4-1.1.war
          asset_content_type: application/java-archive

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make webapps directory
        run: mkdir -p /opt/tomcat/webapps

      - name: Download Java package from GitHub Releases
        run: |
          wget -S --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -O /opt/tomcat/webapps/java-maven4.war \
               "https://github.com/pravesh-77/publish-java-package-with-maven/releases/download/v1.1/java-maven4-1.1.war"

      - name: Restart Tomcat
        run: |
          /opt/tomcat/bin/shutdown.sh && /opt/tomcat/bin/startup.sh
