name: Publish Java Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository -y ppa:linuxuprising/java
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Find WAR file
        id: find_war
        run: |
          war_file=$(find . -type f -name "*.war")
          echo "::set-output name=war_file::$war_file"

      - name: Create Release
        run: |
          gh release create java-maven5-1.1

      - name: Upload WAR to Release
        run: |
          gh release upload java-maven5-1.1 "${{ steps.find_war.outputs.war_file }}" --clobber
