name: Publish Java Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Publish WAR to GitHub Packages
        run: |
          echo "${{ secrets.GH_PACKAGE_TOKEN }}" | gh auth login --with-token
          gh package repo upload pravesh-77/publish-java-package-with-maven \
            --file target/java-maven4-1.1.war \
            --name java-maven4 \
            --version 1.1 \
            --package-type war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make webapps directory
        run: mkdir -p /opt/tomcat/webapps

      - name: Download Java package from GitHub Packages
        run: |
          wget -S --header="Authorization: token ${{ secrets.GH_PACKAGE_TOKEN }}" \
               -O /opt/tomcat/webapps/java-maven4.war \
               -L "https://maven.pkg.github.com/pravesh-77/publish-java-package-with-maven/com/mycompany/app4/java-maven4/1.1/java-maven4-1.1.war"

      - name: Restart Tomcat
        run: |
          /opt/tomcat/bin/shutdown.sh && /opt/tomcat/bin/startup.sh
