name: Publish Java Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in target directory
        run: ls $GITHUB_WORKSPACE/target

      - name: Find WAR file
        id: find_war
        run: |
          war_file=$(find $GITHUB_WORKSPACE/target -type f -name "*.war" | head -n 1)
          echo "::set-output name=war_file::$war_file"

      - name: Create Release
        run: |
          gh auth login --with-token
          gh release create java-maven5-1.1 --title "Java Maven 5 v1.1" --notes "Release for Java Maven 5 v1.1" --target main

      - name: Upload WAR to Release
        run: |
          gh auth login --with-token
          gh release upload java-maven5-1.1 ${{ steps.find_war.outputs.war_file }} --clobber
