name: Publish Java Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Add GitHub CLI repository
        run: sudo apt-add-repository https://cli.github.com/packages

      - name: Update package lists for apt
        run: sudo apt-get update

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Publish WAR to GitHub Packages
        run: |
          gh package repo upload pravesh-77/publish-java-package-with-maven \
            --file target/java-maven5-1.1.war \
            --name java-maven5 \
            --version 1.1 \
            --package-type war
